version: '3.7'

services:
  lamp:
    image: mattrayner/lamp:latest-1804
    restart: always
    container_name: lamp
    volumes:
      - ~/public_html:/app 
      - ./apache2:/etc/apache2
    ports:
      - "80:80"
  db:
    image: mysql:8.0.37
    restart: always
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: 12345678
      MYSQL_DATABASE: test
      MYSQL_USER: sergey 
      MYSQL_PASSWORD: 12345678
    volumes:
      - ~/docker_data/mysql:/var/lib/mysql
    ports:
      - "3306:3306"


